title: <p align="center"> Palash Gupta </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/palash1-gupta/">LinkedIn</a> |
  <a href="https://github.com/gupta-palash">GitHub</a>
  
  <br>   
 1+ years experienced data analytics professional possessing a prolific track record of driving user growth, boosting user retention & enhancing market share by deploying big data ecosystem components, techniques, and best practices. Adept at performing deep dive to gain actionable insights to benefit key stakeholders & facilitate sound decision-making while generating an error-free report. Proficient in data mining and data visualization to deliver compelling business value to clients & successfully execute projects.
  <br>
  </p>



theme: jekyll-theme-minimal
